---
name: Feature Request
about: Suggest a feature that you would like added/improved upon.
title: 'Enhancement: TITLE'
labels: Enhancement
assignees: ''

---

**Is your feature request related to a problem or design oversight? If so, please explain it.**
Provide evidence to help support your claim so we can better understand such as pictures or a video. 

**What is your suggestion?**
Please include as much details as possible. Avoid vague suggestions such as "An app to order food with.". Include as much details as possible such as: "An app that will allow a player to order a food item of their choice and have a player/npc deliver it to them."

**Does your suggestion require any dependencies? (Jobs and Money are framework dependencies.)**

**Do you have any references to help us visualize your suggestion?**
Such as "Here is a link to a similar concept: https://www.youtube.com/watch?v=j5a0jTc9S10 "

**Any additional comments or concerns?**
