---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jouwdesign.
--- DateTime: 24-7-2022 00:10
---

ESX = nil

TriggerEvent("esx:getSharedObject",
        function(obj)
            ESX = obj
        end)



RegisterServerEvent("npwd:TransferMoney")
AddEventHandler("npwd:TransferMoney", function(src, target_iban, amount)
    local xPlayer = ESX.GetPlayerFromId(_source)
end)